on:
  pull_request:
    branches:
    - main
name: main Pull Request
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: create artifacts dir to save test logs
      run: mkdir artifacts
      run: |
       python -m pip install .
    - name: prepare variant definitions
      run: bash .github/scripts/download_variant_definitions.sh
    - name: download annotations
      run: bash .github/scripts/download_annotations.sh
    - name: test PR outputs against previous release
      run: bash .github/scripts/test_PR_against_release.sh
    - uses: actions/upload-artifact@v1
      if: always()
      with:
        name: test_artifacts
        path: artifacts
